### ISSUE TITLE
On mobile view there's difficulty in selecting a day / event. 

### ISSUE THREAD

**Issue by tabish-ali** [tomosterlund/qalendar#233]
Hi, I have installed your calendar for my project, really liked it. I can customize it by overriding CSS. But I found a problem which is causing issue for mobile users and even web users if they increase the day font size.

So let's go to issue without further wasting time.

**So problem was when I clicked or tap the day on calendar it does not select the day unless I click on empty space around the day number. There's span in box that represent day number, it does not select the day if clicked on span. It Only select it when clicked on empty space around it. So it's very frustrating for mobile users, due to small screen size they can't select day easily.**

Image is attached for your convenience.

![Screenshot 2024-01-31 181555](https://github.com/tomosterlund/qalendar/assets/52597760/45e36b9a-351a-4b6f-a8f7-4c7a53252cdc)

**Comment by GitTheCodeAndHitTheRoad** [comment]
I am running into the same issue

**Comment by golam-sorwar** [comment]
I encountered the same issue on mobile view. After applying the custom CSS, the issue has been resolved for me.
```css
span.calendar-month__day-date {
  z-index: 1;
  pointer-events: none;
}
```

**Comment by GitTheCodeAndHitTheRoad** [comment]
> I encountered the same issue on mobile view. After applying the custom CSS, the issue has been resolved for me.
> 
> ```css
> span.calendar-month__day-date {
>   z-index: 1;
>   pointer-events: none;
> }
> ```

Nice solution, perhaps we can make it to be the default value for that css property.

**Comment by GitTheCodeAndHitTheRoad** [comment]
Where exactly did you put the custom css? Did you change it in the _node_modules.dist.src.style.css?_  If I put it simply in the style section it does not work for me:

`<style>
@import "qalendar/dist/style.css";
.v-card__actions {
  padding: 3px;
}

.span.calendar-month__day-date {
  z-index: 1 !important;
  pointer-events: none !important ;
}
</style>`

**Comment by golam-sorwar** [comment]
```css

<style>
@import "qalendar/dist/style.css";
.v-card__actions {
  padding: 3px;
}

span.calendar-month__day-date {
  z-index: 1 !important;
  pointer-events: none !important ;
}
</style>

``` 

try this way remove dot(.) before span
